# Generated by Django 4.1.7 on 2023-04-21 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 2, 12, 30, 219391)),
        ),
    ]
